config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users
    resources :tournaments do
      member do
        patch :enable_change
      end
    end
    #patch 'tournaments/:id/enable_change' => 'application#enable_change', as: 'enable_change_tournament'

    root :to => "home#index"
    resources :users
    post 'users/new_user' => 'users#new_user'
    get 'users/:id/change_password_yourself' => 'users#change_password_yourself', as: 'change_password'
    get 'tournaments/:id/generate_calendar' => 'tournaments#generate_calendar', as: 'generate_calendar'
    resources :teams
    resources :articles do
      member do
        patch :enable_change
      end
    end
    resources :announcements
    resources :statistics
    resources :calendars
    resources :players
    resources :games
    resources :game_details
    resources :albums
    get 'calendars/get_teams_by_tournament/:team_id' => 'calendars#get_teams_by_tournament', as: 'teams_by_tournament'
    get 'players/:id/get_players' => 'players#get_players', as: 'get_players'
    post 'games/game_details' => 'games#game_details', as: 'save_game_details'

    match "/404", to: "errors#not_found", via: :all, as: :not_found
    match "/500", to: "errors#internal_server_error", via: :all
  end
end

app/models/announcement.rb
class Announcement < ApplicationRecord
  belongs_to :user

  has_one_attached :pdf_es_file
  validates_with FileValidator::PDFValidator, field_name: :pdf_es_file

  has_one_attached :pdf_en_file
  validates_with FileValidator::PDFValidator, field_name: :pdf_en_file

  has_one_attached :image
  validates_with FileValidator::ImageValidator, image_field_name: :image

  translates :title, :description
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  load_and_authorize_resource
  before_action :set_announcement, only: %i[ show edit update destroy ]

  # GET /announcements or /announcements.json
  def index
    @announcements = Announcement.all
  end

  # GET /announcements/1 or /announcements/1.json
  def show
  end

  # GET /announcements/new
  def new
    @announcement = Announcement.new
  end

  # GET /announcements/1/edit
  def edit
  end

  # POST /announcements or /announcements.json
  def create
    @announcement = Announcement.new(announcement_params)
    @announcement.user = current_user

    respond_to do |format|
      if @announcement.save
        format.html { redirect_to announcement_url(@announcement), notice: "Announcement was successfully created." }
        format.json { render :show, status: :created, location: @announcement }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /announcements/1 or /announcements/1.json
  def update
    respond_to do |format|
      if @announcement.update(announcement_params)
        format.html { redirect_to announcement_url(@announcement), notice: "Announcement was successfully updated." }
        format.json { render :show, status: :ok, location: @announcement }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /announcements/1 or /announcements/1.json
  def destroy
    @announcement.destroy

    respond_to do |format|
      format.html { redirect_to announcements_url, notice: "Announcement was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_announcement
      @announcement = Announcement.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def announcement_params
      params.require(:announcement).permit(:title, :description, :pdf_es_file, :pdf_en_file, :image)
    end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/views/announcements/_announcement.html.erb
<div id="<%= dom_id announcement %>">
  <p>
    <strong>Title:</strong>
    <%= announcement.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= announcement.description %>
  </p>

  <p>
    <strong>Esta convocatoria fue hecha por:</strong>
    <%= announcement.user.email %>
  </p>

  <% if announcement.pdf_es_file.present? %>
    <p>
      <strong>Vista del PDF en español de la convocatoria:</strong>
      <%= link_to announcement.pdf_es_file.filename, rails_blob_path(announcement.pdf_es_file, disposition: 'preview') %>
    </p>

    <p>
      <strong>Descarga del PDF en español de la convocatoria:</strong>
      <%= link_to announcement.pdf_es_file.filename, rails_blob_path(announcement.pdf_es_file, disposition: 'attachment') %>
    </p>
  <% end %>

  <% if announcement.pdf_en_file.present? %>
    <p>
      <strong>Vista del PDF en ingles de la convocatoria:</strong>
      <%= link_to announcement.pdf_en_file.filename, rails_blob_path(announcement.pdf_en_file, disposition: 'preview') %>
    </p>

    <p>
      <strong>Descarga del PDF en ingles de la convocatoria:</strong>
      <%= link_to announcement.pdf_en_file.filename, rails_blob_path(announcement.pdf_en_file, disposition: 'attachment') %>
    </p>
  <% end %>

</div>

app/views/announcements/_form.html.erb
<div class="px-3 py-2 border rounded-bottom">
  <%= form_with(model: announcement) do |form| %>
    <% if announcement.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(announcement.errors.count, "error") %> prohibited this announcement from being saved:</h2>

        <ul>
          <% announcement.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mb-3">
      <%= form.label :title, class: "form-label" %>
      <%= form.text_field :title, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.label :description, class: "form-label" %>
      <%= form.text_area :description, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.label 'PDF de la convocatoria en español', class: "form-label" %>
      <% if announcement.pdf_es_file.present? %>
        arcivo actual: <strong> <%= announcement.pdf_es_file.filename %> </strong> <br>
      <% end %>
      <%= form.file_field :pdf_es_file, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.label 'PDF de la convocatoria en ingles', class: "form-label" %>
      <% if announcement.pdf_en_file.present? %>
        arcivo actual: <strong> <%= announcement.pdf_en_file.filename %> </strong> <br>
      <% end %>
      <%= form.file_field :pdf_en_file, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.label 'Imagen de la convocatoria', class: "form-label" %>
      <% if announcement.image.present? %>
        <%= image_tag announcement.image, style: "display: block" %>
      <% end %>
      <%= form.file_field :image, class: "form-control" %>
    </div>

    <div>
      <%= form.submit class: "btn btn-primary mb-2" %>
    </div>
  <% end %>
</div>

app/views/announcements/edit.html.erb
<div class="shadow">
  <div class="border rounded-top border-bottom-0">
    <h1 class="text-center m-0 py-1">Editing announcement</h1>
  </div>
  <%= render "form", announcement: @announcement %>
</div>

<br>

<div>
  <%= link_to "Show this announcement", @announcement, class: 'btn btn-outline-success' %>
  <%= link_to "Back to announcements", announcements_path, class: 'btn btn-outline-secondary' %>
</div>

app/views/announcements/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="shadow p-3 rounded-3">
  <h1 class="text-center border-bottom pb-2">
    Announcements
    <a href="<%= new_announcement_path %>" style="text-decoration: none" class="ms-3">
      <i class="fa-solid fa-circle-plus fa-xs"></i>
    </a>
  </h1>

  <div id="announcements" class="mt-2 row row-cols-1 row-cols-sm-2 row-cols-lg-3 row-cols-xl-4 g-3">
    <% @announcements.each do |announcement| %>
      <div class="col">
        <div class="card">
          <a href="<%= announcement_path(announcement) %>">
            <% if announcement.image.present? %>
              <%= image_tag announcement.image, class: 'card-img-top' %>
            <% end %>
          </a>
          <div class="card-body">
            <h5 class="card-title">
              <a href="<%= announcement_path(announcement) %>" class="link-dark" style="text-decoration: none">
                <%= announcement.title.truncate(50) %>
              </a>
            </h5>
            <p class="card-text">
              <%= announcement.description.truncate(90) %>
              <a href="<%= announcement_path(announcement) %>"> Leer más. </a>
            </p>
          </div>
          <div class="card-footer">
            <small class="text-body-secondary">
              Creada el <%= announcement.created_at.strftime('%b %d, %Y') %>
              <br>
              Ultima modificación <%= announcement.updated_at.strftime('%b %d, %Y') %>
              <br>
              Escrita por <%= announcement.user.full_name.truncate(28) %>
              <br>
              <div class="row ms-0 mt-1">
                <div class="border rounded-circle position-relative bg-white" style="width: 30px; height: 30px">
                  <a href="<%= edit_announcement_path(announcement) %>" style="text-decoration: none" class="link-success position-absolute top-50 start-50 translate-middle">
                    <i class="fa-solid fa-pen-to-square"></i>
                  </a>
                </div>
                <div class="border rounded-circle position-relative bg-white ms-1" style="width: 30px; height: 30px">
                  <a href="/" style="text-decoration: none" class="link-danger position-absolute top-50 start-50 translate-middle">
                    <i class="fa-solid fa-eye-slash"></i>
                  </a>
                </div>
              </div>
            </small>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <%= link_to "New announcement", new_announcement_path, class: 'btn btn-primary mt-3' %>
</div>

app/views/announcements/new.html.erb
<div class="shadow">
  <div class="border rounded-top border-bottom-0">
    <h1 class="text-center m-0 py-1">New announcement</h1>
  </div>

  <%= render "form", announcement: @announcement %>
</div>

<br>

<div>
  <%= link_to "Back to announcements", announcements_path, class: 'btn btn-outline-secondary' %>
</div>

app/views/announcements/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="shadow p-2 pt-2 rounded-2">
  <h3 class="mb-0">
    <a href="<%= announcements_path %>" style="text-decoration: none">
      <i class="fa-regular fa-circle-left fa-sm"></i>
    </a><%= @announcement.title %>
  </h3>
  <p class="ms-2 text-secondary"> Convocatoria creada el <%= @announcement.created_at.strftime('%b %d, %Y') %> </p>
  <% if @announcement.image.present? %>
    <%= image_tag @announcement.image, class: 'img-fluid rounded-2 w-75 mb-1 d-block mx-auto' %>
  <% end %>
  <p class="my-2 border-top border-2"><%= simple_format @announcement.description %></p>

  <h5>Archivos de la noticia</h5>

  <div class="row row-cols-1 row-cols-md-2 g-2 mb-3">
    <% if @announcement.pdf_es_file.present? %>
      <div class="col">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title"> <%= @announcement.pdf_es_file.filename %> </h5>
            <p class="card-text">Archivo en español</p>
            <%= link_to(
                  'Ver archivo',
                  rails_blob_path(@announcement.pdf_es_file, disposition: 'preview'),
                  class: 'card-link'
                ) %>
            <%= link_to(
                  'Descargar',
                  rails_blob_path(@announcement.pdf_es_file, disposition: 'attachment'),
                  class: 'card-link'
                ) %>
          </div>
        </div>
      </div>
    <% end %>

    <% if @announcement.pdf_en_file.present? %>
      <div class="col">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title"> <%= @announcement.pdf_en_file.filename %> </h5>
            <p class="card-text">Archivo en ingles</p>
            <%= link_to(
                  'Ver archivo',
                  rails_blob_path(@announcement.pdf_en_file, disposition: 'preview'),
                  class: 'card-link'
                ) %>
            <%= link_to(
                  'Descargar',
                  rails_blob_path(@announcement.pdf_en_file, disposition: 'attachment'),
                  class: 'card-link'
                ) %>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <p class="ms-2 text-secondary mb-0"> Ultima modificación <%= @announcement.updated_at.strftime('%b %d, %Y') %> </p>
  <p class="ms-2 text-secondary mt-0"> Convocatoria escrita por <%= @announcement.user.full_name %> </p>

  <%= link_to "Back to announcements", announcements_path, class: 'btn btn-outline-secondary' %>
  <%= link_to "Edit this announcement", edit_announcement_path(@announcement), class: 'btn btn-outline-info' %>
</div>

<div>
  <%= button_to "Destroy this announcement", @announcement, method: :delete, class: 'btn btn-outline-danger mt-3' %>
</div>