config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users
    resources :tournaments do
      member do
        patch :enable_change
      end
    end
    #patch 'tournaments/:id/enable_change' => 'application#enable_change', as: 'enable_change_tournament'

    root :to => "home#index"
    resources :users
    post 'users/new_user' => 'users#new_user'
    get 'users/:id/change_password_yourself' => 'users#change_password_yourself', as: 'change_password'
    get 'tournaments/:id/generate_calendar' => 'tournaments#generate_calendar', as: 'generate_calendar'
    resources :teams
    resources :articles do
      member do
        patch :enable_change
      end
    end
    resources :announcements
    resources :statistics
    resources :calendars
    resources :players
    resources :games
    resources :game_details
    resources :albums
    get 'calendars/get_teams_by_tournament/:team_id' => 'calendars#get_teams_by_tournament', as: 'teams_by_tournament'
    get 'players/:id/get_players' => 'players#get_players', as: 'get_players'
    post 'games/game_details' => 'games#game_details', as: 'save_game_details'

    match "/404", to: "errors#not_found", via: :all, as: :not_found
    match "/500", to: "errors#internal_server_error", via: :all
  end
end

app/models/statistic.rb
class Statistic < ApplicationRecord
  belongs_to :user

  has_one_attached :pdf_es_file
  validates_with FileValidator::PDFValidator, field_name: :pdf_es_file

  has_one_attached :pdf_en_file
  validates_with FileValidator::PDFValidator, field_name: :pdf_en_file

  has_one_attached :image
  validates_with FileValidator::ImageValidator, image_field_name: :image

  translates :title, :description
end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController
  load_and_authorize_resource
  before_action :set_statistic, only: %i[ show edit update destroy ]

  # GET /statistics or /statistics.json
  def index
    @statistics = Statistic.all
  end

  # GET /statistics/1 or /statistics/1.json
  def show
  end

  # GET /statistics/new
  def new
    @statistic = Statistic.new
  end

  # GET /statistics/1/edit
  def edit
  end

  # POST /statistics or /statistics.json
  def create
    @statistic = Statistic.new(statistic_params)
    @statistic.user = current_user

    respond_to do |format|
      if @statistic.save
        format.html { redirect_to statistic_url(@statistic), notice: "Statistic was successfully created." }
        format.json { render :show, status: :created, location: @statistic }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @statistic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statistics/1 or /statistics/1.json
  def update
    respond_to do |format|
      if @statistic.update(statistic_params)
        format.html { redirect_to statistic_url(@statistic), notice: "Statistic was successfully updated." }
        format.json { render :show, status: :ok, location: @statistic }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @statistic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statistics/1 or /statistics/1.json
  def destroy
    @statistic.destroy

    respond_to do |format|
      format.html { redirect_to statistics_url, notice: "Statistic was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_statistic
      @statistic = Statistic.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def statistic_params
      params.require(:statistic).permit(:title, :description, :pdf_es_file, :pdf_en_file, :image)
    end
end

app/helpers/statistics_helper.rb
module StatisticsHelper
end

app/views/statistics/_form.html.erb
<div class="px-3 py-2 border rounded-bottom">
  <%= form_with(model: statistic) do |form| %>
    <% if statistic.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(statistic.errors.count, "error") %> prohibited this statistic from being saved:</h2>

        <ul>
          <% statistic.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mb-3">
      <%= form.label :title, class: "form-label" %>
      <%= form.text_field :title, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.label :description, class: "form-label" %>
      <%= form.text_area :description, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.label 'PDF de la estadistica en español', class: "form-label" %>
      <% if statistic.pdf_es_file.present? %>
        Arcivo actual: <strong> <%= statistic.pdf_es_file.filename %> </strong> <br>
      <% end %>
      <%= form.file_field :pdf_es_file, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.label 'PDF de la estadistica en ingles', class: "form-label" %>
      <% if statistic.pdf_en_file.present? %>
        Arcivo actual: <strong> <%= statistic.pdf_en_file.filename %> </strong> <br>
      <% end %>
      <%= form.file_field :pdf_en_file, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.label 'Imagen de la noticia', class: "form-label" %>
      <% if statistic.image.present? %>
        <%= image_tag statistic.image, style: "display: block" %>
      <% end %>
      <%= form.file_field :image, class: "form-control" %>
    </div>

    <div>
      <%= form.submit class: "btn btn-primary mb-2" %>
    </div>
  <% end %>
</div>

app/views/statistics/_statistic.html.erb
<div id="<%= dom_id statistic %>">
  <p>
    <strong>Title:</strong>
    <%= statistic.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= statistic.description %>
  </p>

  <p>
    <strong>Esta estadistica fue hecha por:</strong>
    <%= statistic.user.email %>
  </p>

  <% if statistic.pdf_es_file.present? %>
    <p>
      <strong>Vista del PDF en español de la estadistica:</strong>
      <%= link_to statistic.pdf_es_file.filename, rails_blob_path(statistic.pdf_es_file, disposition: 'preview') %>
    </p>

    <p>
      <strong>Descarga del PDF en español de la estadistica:</strong>
      <%= link_to statistic.pdf_es_file.filename, rails_blob_path(statistic.pdf_es_file, disposition: 'attachment') %>
    </p>
  <% end %>

  <% if statistic.pdf_en_file.present? %>
    <p>
      <strong>Vista del PDF en ingles de la estadistica:</strong>
      <%= link_to statistic.pdf_en_file.filename, rails_blob_path(statistic.pdf_en_file, disposition: 'preview') %>
    </p>

    <p>
      <strong>Descarga del PDF en ingles de la estadistica:</strong>
      <%= link_to statistic.pdf_en_file.filename, rails_blob_path(statistic.pdf_en_file, disposition: 'attachment') %>
    </p>
  <% end %>

</div>

app/views/statistics/edit.html.erb
<div class="shadow">
  <div class="border rounded-top border-bottom-0">
    <h1 class="text-center m-0 py-1">Editing statistic</h1>
  </div>
  <%= render "form", statistic: @statistic %>
</div>

<br>

<div>
  <%= link_to "Show this statistic", @statistic, class: 'btn btn-outline-success' %>
  <%= link_to "Back to statistics", statistics_path, class: 'btn btn-outline-secondary' %>
</div>

app/views/statistics/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="shadow p-3 rounded-3">
  <h1 class="text-center border-bottom pb-2">
    Statistics
    <a href="<%= new_statistic_path %>" style="text-decoration: none" class="ms-3">
      <i class="fa-solid fa-circle-plus fa-xs"></i>
    </a>
  </h1>

  <div id="statistics" class="mt-2 row row-cols-1 row-cols-sm-2 row-cols-lg-3 row-cols-xl-4 g-3">
    <% @statistics.each do |statistic| %>
      <div class="col">
        <div class="card">
          <a href="<%= statistic_path(statistic) %>">
            <% if statistic.image.present? %>
              <%= image_tag statistic.image, class: 'card-img-top' %>
            <% end %>
          </a>
          <div class="card-body">
            <h5 class="card-title">
              <a href="<%= statistic_path(statistic) %>" class="link-dark" style="text-decoration: none">
                <%= statistic.title.truncate(50) %>
              </a>
            </h5>
            <p class="card-text">
              <%= statistic.description.truncate(90) %>
              <a href="<%= statistic_path(statistic) %>"> Leer más. </a>
            </p>
          </div>
          <div class="card-footer">
            <small class="text-body-secondary">
              Creada el <%= statistic.created_at.strftime('%b %d, %Y') %>
              <br>
              Ultima modificación <%= statistic.updated_at.strftime('%b %d, %Y') %>
              <br>
              Escrita por <%= statistic.user.full_name.truncate(28) %>
              <br>
              <div class="row ms-0 mt-1">
                <div class="border rounded-circle position-relative bg-white" style="width: 30px; height: 30px">
                  <a href="<%= edit_statistic_path(statistic) %>" style="text-decoration: none" class="link-success position-absolute top-50 start-50 translate-middle">
                    <i class="fa-solid fa-pen-to-square"></i>
                  </a>
                </div>
                <div class="border rounded-circle position-relative bg-white ms-1" style="width: 30px; height: 30px">
                  <a href="/" style="text-decoration: none" class="link-danger position-absolute top-50 start-50 translate-middle">
                    <i class="fa-solid fa-eye-slash"></i>
                  </a>
                </div>
              </div>
            </small>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <%= link_to "New statistic", new_statistic_path, class: 'btn btn-primary mt-3' %>
</div>

app/views/statistics/new.html.erb
<div class="shadow">
  <div class="border rounded-top border-bottom-0">
    <h1 class="text-center m-0 py-1">New statistic</h1>
  </div>
  <%= render "form", statistic: @statistic %>
</div>

<br>

<div>
  <%= link_to "Back to statistics", statistics_path, class: 'btn btn-outline-secondary' %>
</div>

app/views/statistics/show.html.erb
<div class="shadow p-2 pt-2 rounded-2">
  <h3 class="mb-0">
    <a href="<%= statistics_path %>" style="text-decoration: none">
      <i class="fa-regular fa-circle-left fa-sm"></i>
    </a><%= @statistic.title %>
  </h3>
  <p class="ms-2 text-secondary"> Convocatoria creada el <%= @statistic.created_at.strftime('%b %d, %Y') %> </p>
  <% if @statistic.image.present? %>
    <%= image_tag @statistic.image, class: 'img-fluid rounded-2 w-75 mb-1 d-block mx-auto' %>
  <% end %>
  <p class="my-2 border-top border-2"><%= simple_format @statistic.description %></p>

  <h5>Archivos de la noticia</h5>

  <div class="row row-cols-1 row-cols-md-2 g-2 mb-3">
    <% if @statistic.pdf_es_file.present? %>
      <div class="col">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title"> <%= @statistic.pdf_es_file.filename %> </h5>
            <p class="card-text">Archivo en español</p>
            <%= link_to(
                  'Ver archivo',
                  rails_blob_path(@statistic.pdf_es_file, disposition: 'preview'),
                  class: 'card-link'
                ) %>
            <%= link_to(
                  'Descargar',
                  rails_blob_path(@statistic.pdf_es_file, disposition: 'attachment'),
                  class: 'card-link'
                ) %>
          </div>
        </div>
      </div>
    <% end %>

    <% if @statistic.pdf_en_file.present? %>
      <div class="col">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title"> <%= @statistic.pdf_en_file.filename %> </h5>
            <p class="card-text">Archivo en ingles</p>
            <%= link_to(
                  'Ver archivo',
                  rails_blob_path(@statistic.pdf_en_file, disposition: 'preview'),
                  class: 'card-link'
                ) %>
            <%= link_to(
                  'Descargar',
                  rails_blob_path(@statistic.pdf_en_file, disposition: 'attachment'),
                  class: 'card-link'
                ) %>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <p class="ms-2 text-secondary mb-0"> Ultima modificación <%= @statistic.updated_at.strftime('%b %d, %Y') %> </p>
  <p class="ms-2 text-secondary mt-0"> Estadistica escrita por <%= @statistic.user.full_name %> </p>

  <%= link_to "Back to statistics", statistics_path, class: 'btn btn-outline-secondary' %>
  <%= link_to "Edit this statistic", edit_statistic_path(@statistic), class: 'btn btn-outline-info' %>
</div>

<div>
  <%= button_to "Destroy this statistic", @statistic, method: :delete, class: 'btn btn-outline-danger mt-3' %>
</div>